# Site settings
title: 兰缘小妖的秘密花园
logo: logo.png
email: lanyuanxiaoyao@qq.com
description: > # this means to ignore newlines until "baseurl:"
  世界上有一条最孤独的鲸鱼叫做Alice
url: "http://www.lanyuanxiaoyao.cn"
baseurl: ""

# Build settings
markdown: kramdown
