# Site settings
title: 兰缘小妖的秘密花园
logo: logo.png
email: lanyuanxiaoyao@qq.com
description: > # this means to ignore newlines until "baseurl:"
  不谈代码 记录人生
url: "http://www.lanyuanxiaoyao.cn"
baseurl: ""

# Build settings
markdown: kramdown
